name: Resize PNG and JPG Images in Specific Folders

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  resize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git to handle large pushes
        run: |
          git config --global http.postBuffer 524288000

      - name: Install ImageMagick
        run: sudo apt-get install -y imagemagick

      - name: Find and Resize PNG and JPG Images in srp, snp
        run: |
          for folder in srp snp; do
            # Trova e ridimensiona immagini PNG
            find "$folder" -type f \( -name "*.png" -o -name "*.jpg" \) | while read image; do
              echo "Resizing $image"
              convert "$image" -resize 417x250 "$image"
            done
          done

      - name: Commit resized images
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A  # Aggiunge tutte le modifiche
          git commit -m "Resize PNG and JPG images in SNP and SRF" || echo "No changes to commit"
          git push
