name: Zip Git Folders

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zip-folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create zip folder (if needed)
        run: mkdir -p zip

      - name: Zip folders
        run: |
          for dir in logo/CRYPT logo/EMU logo/IPTV logo/PROVIDER logo/SAT logo/SNP logo/SRF logo/VOD logo/VOD/ANIMATION- logo/VOD/GENRE logo/VOD/SERIES; do
            if [ -d "$dir" ]; then
              zip -r "zip/$(basename $dir).zip" "$dir"
            fi
          done

      - name: Commit and push zipped files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add zip/*.zip
          git commit -m "Added zipped folders" || echo "No changes to commit"
          git push || echo "No changes to push"
