name: Zip Git Folders

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zip-folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create zip folder (if needed)
        run: mkdir -p zip

      - name: Zip folders
        run: |
          for dir in logos/CRYPT logos/EMU logos/IPTV logos/PROVIDER logos/SAT logos/SNP logos/SRF logos/VOD; do
            if [ -d "$dir" ]; then
              zip -r "$(basename $dir).zip" "$dir"
            fi
          done

      - name: Check if zip files exist
        id: check_zip
        run: |
          if ls *.zip 1> /dev/null 2>&1; then
            echo "ZIP_FILES_EXIST=true" >> $GITHUB_ENV
          else
            echo "ZIP_FILES_EXIST=false" >> $GITHUB_ENV
          fi

      - name: Commit and push zipped files
        if: env.ZIP_FILES_EXIST == 'true'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add *.zip
          git commit -m "Added zipped folders"
          git push
