name: Fix Filenames

on:
  #schedule:
    # - cron: '0 3 * * 1'  # Ogni lunedì alle 03:00 UTC
  workflow_dispatch:  # Permette esecuzione manuale

jobs:
  rename-and-delete-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Rename files with double extension
        run: |
          find . -type f -name "*.png.png" | while IFS= read -r file; do
            new_name=$(echo "$file" | sed 's/.png.png$/.png/')  # Rimuove l'estensione doppia
            if [ "$file" != "$new_name" ]; then
              # Crea la directory di destinazione se non esiste
              dest_dir=$(dirname "$new_name")
              mkdir -p "$dest_dir"
              mv "$file" "$new_name"  # Rinomina solo se il nuovo nome è diverso
              echo "Renamed: $file -> $new_name"
            fi
          done

      - name: Fix filenames: remove dashes, spaces, and other unwanted characters
        run: |
          find . -type f -name "*.png" | while IFS= read -r file; do
            new_name=$(echo "$file" | sed 's/[- ]//g')  # Rimuove trattini e spazi
            if [ "$file" != "$new_name" ]; then
              # Crea la directory di destinazione se non esiste
              dest_dir=$(dirname "$new_name")
              mkdir -p "$dest_dir"
              mv "$file" "$new_name"  # Solo se il nome del file è diverso
              echo "Renamed: $file -> $new_name"
            fi
          done

      - name: Delete files containing parentheses
        run: |
          find . -type f \( -name "*(*" -o -name "*)*" \) -exec rm -v {} +

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add .
          git commit -m "Fixed filenames: renamed double extensions, removed dashes/spaces, and deleted files with parentheses" || echo "No changes to commit"
          git push --force
