name: Fix Filenames

on:
  #schedule:
    # - cron: '0 3 * * 1'  # Ogni lunedì alle 03:00 UTC
  workflow_dispatch:  # Permette esecuzione manuale

jobs:
  rename-and-delete-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Rename files with double extension
        run: |
          find . -type f -name "*.png.png" | while read file; do
            new_name=$(echo "$file" | sed 's/.png.png$/.png/')
            mv "$file" "$new_name"
          done

      - name: Delete files containing parentheses
        run: |
          find . -type f \( -name "*(*" -o -name "*)*" \) -exec rm -v {} +

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add .
          git commit -m "Fixed filenames: renamed double extensions and removed files with parentheses" || echo "No changes to commit"
          git push --force
