name: List Files in Folders

on:
  schedule:
    - cron: '0 2 * * 1'  # Every Monday at 02:00 UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  list-files-in-folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Configure Git to handle large pushes
        run: |
          git config --global http.postBuffer 524288000  # Increase buffer size to 500MB
      - name: Generate file lists
        run: |
          # Create the 'txt' folder if it doesn't exist
          mkdir -p txt

          # Loop through all folders in the repository
          for folder in */; do
            if [ -d "$folder" ]; then
              folder_name=$(basename "$folder")
              txt_file="txt/${folder_name}.txt"
              
              # List files in the folder (including subfolders) and save to a text file
              find "$folder" -type f > "$txt_file"
              echo "File list for folder $folder_name created at $txt_file"
            fi
          done

      - name: Pull the latest changes
        run: |
          # Set git configuration for the commit
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          # Pull latest changes from remote to avoid conflicts
          git pull origin main || echo "No changes to pull"

      - name: Commit and push file lists
        run: |
          # Add the generated text files to git
          git add txt/*.txt
          
          # Commit changes
          git commit -m "Added file lists for folders"
          
          # Push changes to remote, force push in case of conflicts
          git push || git push --force
