name: List Files in Folders

on:
  schedule:
    - cron: '0 2 * * 1'  # Every Monday at 02:00 UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  list-files-in-folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git to handle large pushes
        run: |
          git config --global http.postBuffer 524288000  # Increase buffer size to 500MB

      - name: Remove old .txt files
        run: |
          rm -f txt/*.txt
          echo "Old .txt files removed from the txt folder"

      - name: Generate file lists
        run: |
          # Create the 'txt' folder if it doesn't exist
          mkdir -p txt
          # Loop through all folders in the repository
          for folder in */; do
            if [ -d "$folder" ]; then
              folder_name=$(basename "$folder")
              
              # Skip the 'txt' folder to avoid creating txt.txt
              if [ "$folder_name" != "txt" ]; then
                txt_file="txt/${folder_name}.txt"
                
                # List files in the folder (including subfolders) and save to a text file
                find "$folder" -type f > "$txt_file"
                echo "File list for folder $folder_name created at $txt_file"
              fi
            fi
          done

      - name: Pull the latest changes and merge
        run: |
          git pull origin main --rebase || git pull origin main

      - name: Commit and push file lists
        run: |
          # Configura l'autore e l'email per Git
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      
          # Aggiungi i file txt generati al commit
          git add txt/*.txt
          
          # Commit delle modifiche
          git commit -m "Added file lists for folders" || echo "No changes to commit"
          
          # Push delle modifiche al remote (con push forzato in caso di conflitto)
          git push || git push --force
