name: List Files in Folders

on:
  schedule:
    - cron: '0 2 * * 1'  # Ogni lunedì alle 02:00 UTC
  workflow_dispatch:  # Permette di eseguire manualmente

jobs:
  list-files-in-folders:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Rimuovi i vecchi file .txt (se esistono)
      - name: Remove old .txt files
        run: |
          echo "Checking if txt folder exists..."
          if [ -d "txt" ]; then
            echo "txt folder found. Removing .txt files..."
            rm -f txt/*.txt
            echo "Old .txt files removed from the txt folder."
          else
            echo "No txt folder found, skipping file removal."
          fi

      # 3. Funzione per generare la lista dei file
      - name: Generate file lists for each folder
        run: |
          mkdir -p txt

          # Funzione ricorsiva per elencare i file di una cartella
          generate_file_list() {
            local folder=$1
            local txt_file="txt/${folder}.txt"

            # Aggiungi l'elenco dei file nella cartella corrente
            echo "Elenco dei file in: $folder" >> "$txt_file"
            find "$folder" -maxdepth 1 -type f >> "$txt_file"
            echo "" >> "$txt_file"

            # Cerca eventuali sottocartelle e aggiungi i loro file
            for subfolder in "$folder"*/; do
              if [ -d "$subfolder" ]; then
                subfolder_name=$(basename "$subfolder")
                echo "Elenco dei file in: $subfolder_name" >> "$txt_file"
                find "$subfolder" -maxdepth 1 -type f >> "$txt_file"
                echo "" >> "$txt_file"

                # Chiamata ricorsiva per la sottocartella
                generate_file_list "$subfolder"
              fi
            done
          }

          # Esegui la funzione su tutte le cartelle principali
          for folder in */; do
            if [ -d "$folder" ] && [ "$folder" != "txt/" ]; then
              folder_name=$(basename "$folder")
                                               
                                                  
              generate_file_list "$folder_name"
            fi
          done

      # 4. Commit e push delle modifiche (evita modifiche ai file di workflow)
      - name: Commit e push delle modifiche
        run: |
          git config --global user.email "ekekaz@gmail.com"
          git config --global user.name "Belfagor2005"
          git add txt/*.txt
          git commit -m "Aggiunti file di lista per le cartelle" || echo "Nessuna modifica da commettere"
          git push origin main || echo "Push fallito"
