name: List Files in Folders

on:
  schedule:
    - cron: '0 3 * * 1'  # Monday 03:00 UTC
  workflow_dispatch:

jobs:
  list-files-in-folders:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Remove old .txt files (if they exist)
      - name: Remove old .txt files
        run: |
          echo "Checking if txt folder exists..."
          if [ -d "txt" ]; then
            echo "txt folder found. Removing .txt files..."
            rm -f txt/*.txt
            echo "Old .txt files removed from the txt folder."
          else
            echo "No txt folder found, skipping file removal."
          fi

      # 3. Make file lists for each folder/subfolder
      - name: Generate file lists for folders
        run: |
          mkdir -p txt
          for folder in */; do
            if [ -d "$folder" ] && [ "$folder" != "txt/" ]; then
              folder_name=$(basename "$folder")
              txt_file="txt/${folder_name}.txt"
              find "$folder" -type f > "$txt_file"
              echo "List of files for folder $folder_name created in $txt_file"
            fi
          done

      # 4. Commit and push changes (avoid changes to workflow files)
      - name: Commit and push changes
        run: |
          git config --global user.email "ekekaz@gmail.com"
          git config --global user.name "Belfagor2005"
          git add txt/*.txt
          git commit -m "Added list files for folders" || echo "No changes to make"
          git push origin main || echo "Push failure"
