name: List Files in Folders

on:
  schedule:
    - cron: '0 2 * * 1'  # Ogni lunedì alle 02:00 UTC
  workflow_dispatch:  # Permette di eseguire manualmente

jobs:
  list-files-in-folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Rimuovi vecchi file .txt
        run: |
          rm -f txt/*.txt
          echo "Vecchi file .txt rimossi dalla cartella txt"

      - name: Genera le liste dei file
        run: |
          mkdir -p txt
          for folder in */; do
            if [ -d "$folder" ]; then
              folder_name=$(basename "$folder")
              
              # Skip the 'txt' folder to avoid creating txt.txt
              if [ "$folder_name" != "txt" ]; then
                txt_file="txt/${folder_name}.txt"
                
                # List files in the folder (including subfolders) and save to a text file
                find "$folder" -type f > "$txt_file"
                echo "File list for folder $folder_name created at $txt_file"
              fi
            fi
          done

      - name: Sincronizzare con il repository remoto
        run: |
          git pull origin main || echo "Non ci sono modifiche da sincronizzare"

      - name: Commit e push delle modifiche
        run: |
          git config --global user.email "ekekaz@gmail.com"
          git config --global user.name "Belfagor2005"
          git add txt/*.txt
          git commit -m "Aggiunti file di lista per le cartelle" || echo "Nessuna modifica da commettere"
          git push origin main
