name: Generate File List

on:
  schedule:
    - cron: '0 0 * * 1'  # Ogni lunedì alle 00:00 UTC
  workflow_dispatch:  # Permette di avviarlo manualmente

jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Remove existing txt files
        run:
          rm -rf txt

      - name: Create txt files with file list
        run: |
          mkdir -p txt

          for folder in logos/*; do
            if [ -d "$folder" ]; then
              folder_name=$(basename "$folder")
              txt_file="txt/${folder_name}.txt"

              find "$folder" -type f -name "*.jpg" -o -name "*.png" -o -name "*.gif" | sort > "$txt_file"

              echo "File list for folder $folder_name has been created at $txt_file"
            fi
          done

      - name: Commit and push file lists
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add txt/*.txt
          git commit -m "Added file lists for folders"
          git push || git push --force
