name: List Files in Folders

on:
  schedule:
    - cron: '0 2 * * 1'  # Every Monday at 02:00 UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  list-files-in-folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git to handle large pushes and set author
        run: |
          git config --global http.postBuffer 524288000  # Increase buffer size to 500MB
          git config --global user.email "ekekaz@gmail.com"
          git config --global user.name "Belfagor2005"

      - name: Remove old .txt files
        run: |
          rm -f txt/*.txt
          echo "Old .txt files removed from the txt folder"

      - name: Generate file lists
        run: |
          # Create the 'txt' folder if it doesn't exist
          mkdir -p txt
          # Loop through all folders in the repository
          for folder in */; do
            if [ -d "$folder" ]; then
              folder_name=$(basename "$folder")
              
              # Skip the 'txt' folder to avoid creating txt.txt
              if [ "$folder_name" != "txt" ]; then
                txt_file="txt/${folder_name}.txt"
                
                # List files in the folder (including subfolders) and save to a text file
                find "$folder" -type f > "$txt_file"
                echo "File list for folder $folder_name created at $txt_file"
              fi
            fi
          done

      - name: Pull latest changes
        run: |
          # Pull latest changes from remote to avoid conflicts
          git pull origin main || echo "No changes to pull"

      - name: Add all changes (including file deletions)
        run: |
          # Add all changes including deletions
          git add -A
          
      - name: Commit and push file lists
        run: |
          # Commit changes
          git commit -m "Added file lists for folders" || echo "No changes to commit"
          
          # Push changes to remote, force push in case of conflicts
          git push || git push --force
