name: List Files in Folders

on:
  schedule:
    - cron: '0 2 * * 1'  # Ogni lunedì alle 02:00 UTC
  workflow_dispatch:  # Permette di eseguire manualmente

jobs:
  list-files-in-folders:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Rimuovi i vecchi file .txt (se esistono)
      - name: Remove old .txt files
        run: |
          echo "Checking if txt folder exists..."
          if [ -d "txt" ]; then
            echo "txt folder found. Removing .txt files..."
            rm -f txt/*.txt
            echo "Old .txt files removed from the txt folder."
          else
            echo "No txt folder found, skipping file removal."
          fi

      # 3. Genera la lista dei file per ogni cartella
      - name: Genera le liste dei file
        run: |
          mkdir -p txt
          for folder in */; do
            if [ -d "$folder" ] && [ "$folder" != "txt/" ]; then
              folder_name=$(basename "$folder")
              txt_file="txt/${folder_name}.txt"
              find "$folder" -type f > "$txt_file"
              echo "Lista dei file per la cartella $folder_name creata in $txt_file"
            fi
          done

      # 4. Commit e push delle modifiche (evita modifiche ai file di workflow)
      - name: Commit e push delle modifiche
        run: |
          git config --global user.email "ekekaz@gmail.com"
          git config --global user.name "Belfagor2005"
          git add txt/*.txt
          git commit -m "Aggiunti file di lista per le cartelle" || echo "Nessuna modifica da commettere"
          git push origin main || echo "Push fallito"
