name: Zip Folders

on:
  workflow_dispatch:

jobs:
  zip-folders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git to handle large pushes
        run: |
          git config --global http.postBuffer 524288000  # Increase buffer size to 500MB

      - name: Remove old zip files
        run: |
          mkdir -p zip
          rm -f zip/*.zip

      - name: Create zip files
        run: |
          mkdir -p zip
          for folder in logos/*; do
            if [ -d "$folder" ]; then
              folder_name=$(basename "$folder")
              zip_file="zip/${folder_name}.zip"
              zip -r "$zip_file" "$folder"
              echo "Created zip file: $zip_file"
            fi
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Pull remote changes and rebase local changes
          git pull --rebase origin main

          # Add all changes
          git add -A

          # Commit changes
          git commit -m "Added zipped folders" || echo "No changes to commit"

          # Push changes
          git push origin main
