name: Lowercase Filenames

on:
  workflow_dispatch:

jobs:
  lowercase_filenames:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert filenames to lowercase in ./logos/SNP
        run: |
          find ./logos/SNP -depth -name "*" | while read file; do
            lowercase_file=$(echo "$file" | tr 'A-Z' 'a-z')
            if [ "$file" != "$lowercase_file" ]; then
              temp_file="${lowercase_file}.tmp"
              mv "$file" "$temp_file"
              mv "$temp_file" "$lowercase_file"
              git add "$lowercase_file"
            fi
          done
