name: Lowercase Filenames

on:
  workflow_dispatch:

jobs:
  lowercase_filenames:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git to handle large pushes
        run: |
          git config --global http.postBuffer 524288000  # Aumenta la dimensione del buffer a 500MB

      - name: Ensure SNP directory exists
        run: |
          if [ ! -d "logos/SNP" ]; then
            echo "Directory logos/SNP does not exist. Exiting."
            exit 1
          fi

      - name: Convert filenames to lowercase, remove hyphens and spaces in logos/SNP
        run: |
          find logos/SNP -depth -type f | while read -r file; do
            dir=$(dirname "$file")
            base=$(basename "$file")
            # Controllo se il nome contiene lettere maiuscole
            if [[ "$base" =~ [A-Z] ]]; then
              lowercase_base=$(echo "$base" | tr 'A-Z' 'a-z' | tr -d '-' | tr -d ' ')  # Rimuovo trattini e spazi
              lowercase_file="$dir/$lowercase_base"
              if [ "$file" != "$lowercase_file" ]; then
                mv "$file" "$lowercase_file"
                git add "$lowercase_file"
                git rm -f "$file" || true
              fi
            fi
          done

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git pull --rebase origin main || true  # Aggiungi un pull per recuperare i cambiamenti remoti
          git add -A
          git commit -m "Convert filenames to lowercase and remove hyphens in logos/SNP" || echo "No changes to commit"
          git push origin main
