name: Count and Update Graphic Files

on:
  schedule:
    - cron: '0 2 * * 1'  # Every Monday at 02:00 UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  count-graphic-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git to handle large pushes
        run: |
          git config --global http.postBuffer 524288000  # Increase buffer size to 500MB

      - name: Pull the latest changes
        run: |
          git fetch --all
          git reset --hard origin/main || echo "No changes to pull"

      - name: Count graphic files and update number
        run: |
          # Count the graphic files (png, jpg, gif, svg, etc.)
          GRAPHIC_COUNT=$(find . -type f \( -iname "*.png" -o -iname "*.jpg" -o -iname "*.gif" -o -iname "*.svg" \) | wc -l)

          # Debugging: Show the count to verify it's being calculated correctly
          echo "Graphic files count: $GRAPHIC_COUNT"

          # Create or update the file with the graphic count in the root folder
          echo "Number of graphic files: $GRAPHIC_COUNT" > "NumeroPicons.txt"

          # Check if the string exists and update or append it in README.md
          if grep -q "Number of graphic files:" README.md; then
            echo "Updating number in README.md"
            sed -i "s/Number of graphic files:.*/Number of graphic files: $GRAPHIC_COUNT/" README.md
          else
            echo "Adding number to README.md"
            echo "Number of graphic files: $GRAPHIC_COUNT" >> README.md
          fi

      - name: Check if there are changes to commit
        run: |
          # Check if there are changes in README.md or NumeroPicons.txt
          git diff --exit-code README.md || echo "Changes detected in README.md"
          git diff --exit-code NumeroPicons.txt || echo "Changes detected in NumeroPicons.txt"

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Add the updated files (README.md and NumeroPicons.txt)
          git add README.md NumeroPicons.txt

          # Commit the changes only if there are modifications
          git commit -m "Updated number of graphic files in README.md and NumeroPicons.txt" || echo "No changes to commit"

          # Push the changes (with force in case of conflicts)
          git push --force
