name: Count Graphic Files

on:
  schedule:
    - cron: '0 2 * * 1'  # lunedì 02:00 UTC
  workflow_dispatch:

jobs:
  count-graphic-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Count graphic files
        run: |
          extensions="\( -name '*.png' -o -name '*.jpg' -o -name '*.jpeg' -o -name '*.gif' -o -name '*.svg' \)"
          
          total_files=$(find . -type f $extensions | wc -l)

          mkdir -p txt

          txt_file="txt/Number Picons (${total_files}).txt"
          echo "Number of graphic files: $total_files" > "$txt_file"
          
          echo "File created: $txt_file with $total_files graphic files."

      - name: Commit and push file with graphic count
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add txt/*.txt
          git commit -m "Added number of graphic files"
          git push || git push --force
