name: Count and Update Graphic Files

on:
  schedule:
    - cron: '0 2 * * 1'  # Ogni lunedì alle 02:00 UTC
  workflow_dispatch:  # Permette l'avvio manuale

jobs:
  count-graphic-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git to handle large pushes
        run: |
          git config --global http.postBuffer 524288000  # Aumenta la dimensione del buffer a 500MB

      - name: Pull the latest changes
        run: |
          git fetch --all
          git reset --hard origin/main || echo "No changes to pull"

      - name: Count graphic files and update number
        run: |
          # Conta i file grafici (png, jpg, gif, svg, ecc.)
          GRAPHIC_COUNT=$(find . -type f \( -iname "*.png" -o -iname "*.jpg" -o -iname "*.gif" -o -iname "*.svg" \) | wc -l)

          # Debugging: Mostra il conteggio per verificare che sia calcolato correttamente
          echo "Graphic files count: $GRAPHIC_COUNT"

          # Crea o aggiorna il file con il conteggio dei file grafici nella cartella root
          echo "Number of graphic files: $GRAPHIC_COUNT" > "NumeroPicons.txt"

          # Controlla se la stringa esiste e aggiorna o aggiungila in README.md
          if grep -q "Number of graphic files:" README.md; then
            echo "Updating number in README.md"
            sed -i "s/Number of graphic files:.*/Number of graphic files: $GRAPHIC_COUNT/" README.md
          else
            echo "Adding number to README.md"
            echo "Number of graphic files: $GRAPHIC_COUNT" >> README.md
          fi

      - name: Check if there are changes to commit
        run: |
          # Controlla se ci sono modifiche in README.md o NumeroPicons.txt
          git diff --exit-code README.md || echo "Changes detected in README.md"
          git diff --exit-code NumeroPicons.txt || echo "Changes detected in NumeroPicons.txt"

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Aggiungi i file aggiornati (README.md e NumeroPicons.txt)
          git add README.md NumeroPicons.txt

          # Committa le modifiche solo se ci sono cambiamenti
          git commit -m "Updated number of graphic files in README.md and NumeroPicons.txt" || echo "No changes to commit"

          # Push delle modifiche (con --force in caso di conflitti)
          git push --force
