name: Restore Deleted Files and Clean Up

on:
  workflow_dispatch:  # Avvio manuale

jobs:
  restore-and-clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Rename files with double extensions
        run: |
          find . -type f -name "*.png.png" | while read file; do
            mv "$file" "${file%.png.png}.png"
          done

      - name: Remove files with parentheses in the name
        run: |
          find . -type f \( -name "*(*" -o -name "*)*" \) -delete

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Restored deleted files, renamed .png.png files, and removed files with parentheses" || echo "No changes to commit"
          git push || echo "No changes to push"
