name: CLOSE-Resize PNG and JPG Images in Specific Folders

on:
  workflow_dispatch

jobs:
  resize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git to handle large pushes
        run: |
          git config --global http.postBuffer 524288000
      - name: Install ImageMagick
        run: sudo apt-get install -y imagemagick

      - name: Resize PNG and JPG Images in SNP and SRF
        run: |
          for folder in logos/SNP logos/SRF; do
            if [ -d "$folder" ]; then
              echo "Resizing images in folder: $folder"
              # Prendi solo i primi 10 file
              find "$folder" -type f \( -name "*.png" -o -name "*.jpg" \) | head -n 10 | while read image; do
                # Verifica che il file esista
                if [ ! -f "$image" ]; then
                  echo "File non trovato: $image"
                  continue
                fi
                
                # Check formato immagini
                current_size=$(identify -format "%wx%h" "$image" 2>/dev/null)
                if [ $? -ne 0 ]; then
                  echo "Errore nel recuperare le dimensioni dell'immagine $image"
                  continue
                fi

                if [ "$current_size" == "220x132" ]; then
                  echo "Skipping $image (already 220x132)"
                  continue  # skip file if 220x132
                fi

                echo "Before resizing: $current_size"
                convert "$image" -resize 220x132! "$image"
                echo "After resizing: $(identify -format "%wx%h" $image)"
              done
            else
              echo "Directory $folder does not exist!"
            fi
          done
      - name: Commit resized images
        run: |
          git con
