name: Resize PNG and JPG Images in Specific Folders

on:
  workflow_dispatch

jobs:
  resize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git to handle large pushes
        run: |
          git config --global http.postBuffer 524288000
      - name: Install ImageMagick
        run: sudo apt-get install -y imagemagick

      - name: Resize PNG and JPG Images in SNP and SRF
        run: |
          for folder in logos/IPTV logos/SNP logos/SRF; do
            if [ -d "$folder" ]; then
              echo "Resizing images in folder: $folder"
              find "$folder" -type f \( -name "*.png" -o -name "*.jpg" \) | while read image; do
                # check format files
                current_size=$(identify -format "%wx%h" "$image")
                if [ "$current_size" == "417x250" ]; then
                  echo "Skipping $image (already 417x250)"
                  continue  # skip file if 417x250
                fi
                echo "Before resizing: $current_size"
                # convert "$image" -resize 417x250 "$image"
		convert "$image" -resize 417x250! "$image"
  		echo "After resizing: $(identify -format "%wx%h" $image)"
              done
            else
              echo "Directory $folder does not exist!"
            fi
          done
      - name: Commit resized images
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull origin main
          git add -A  # Aggiunge tutte le modifiche
          git commit -m "Resize PNG and JPG images in SNP and SRF" || echo "No changes to commit"
          git push
