name: Resize PNG and JPG Images in Specific Folders

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  resize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install ImageMagick
        run: sudo apt-get install -y imagemagick

      - name: Resize PNG and JPG Images in srp and snp
        run: |
          for folder in srp snp; do
            find "$folder" -type f \( -name "*.png" -o -name "*.jpg" \) | while read image; do
              echo "Resizing $image"
              convert "$image" -resize 417x250 "$image"
            done
          done

      - name: Commit resized images
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Resize PNG and JPG images in srp and snp"
          git push
