name: Resize PNG Images in Specific Folders

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  resize:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git to handle large pushes
        run: |
          git config --global http.postBuffer 524288000  # Increase buffer size to 500MB	

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install ImageMagick
        run: sudo apt-get install -y imagemagick

      - name: Find and Resize PNG Images in srp, snp, svg
        run: |
          for folder in srp snp; do
            find "$folder" -type f -name "*.png" | while read image; do
              echo "Resizing $image"
              convert "$image" -resize 417x250 "$image"
            done
          done

      - name: Commit resized images
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Resize PNG images in srp, snp, svg"
          git push
